/**
 * 社区与灵感广场内置精选案例集 (Builtin Community Cases)
 * 参考即梦 AI (Jimeng AI) 作品案例系统设计规范：
 * 包含完整提示词、智能参考原图、生成模型、画面比例、详细采样参数、作者信息及交互数据。
 */

export const BUILTIN_COMMUNITY_CASES = [
  {
    id: '7681561564197031193',
    creation_id: 'cr_beer_poster_ryusei_01',
    user_id: 'usr_jimeng_ai',
    title: '竖版啤酒艺术海报',
    description: '潮流实验性设计 (Anti-Design)，工业平面风格，点阵网点与解构美学。',
    media_type: 'image',
    media_url: '/assets/community/case-beer-poster.webp',
    cover_url: '/assets/community/case-beer-poster.webp',
    prompt: '一张3:4竖版啤酒艺术海报，潮流实验性设计 (Anti-Design)，工业平面风格。【产品展示】@image1 啤酒罐体以居中剪影方式呈现于画面正中，罐体表面经过点阵打印效果艺术化处理；四周散布技术参数文字和装饰符号。【构图】顶部和底部各有巨大黑色粗体字被画面边缘"切断"，形成视觉张力；罐体居中，周围留有呼吸空间；四角和边缘散布小号说明文字和几何符号，形成信息框架。【色彩方案】银白色罐身为画面焦点，深蓝色块作为背景局部装饰，大面积黑色文字，金黄色作为点缀装饰色；整体底色为带有磨损质感的灰白色，模拟复古复印纸纸张感。【光影】罐体经过点阵化/半调网点艺术处理，非真实光影而是图形化表现；整体画面带有颗粒状复印机纸张质感和轻微磨损痕迹；无传统摄影光影，以平面图形语言为主。【文字排版】顶部超大黑体日文"初搾り"被上边缘切断只显示下半部分；底部超大黑体英文"RYUSEI"被下边缘切断只显示上半部分；罐身上方英文"BREWED FOR GREAT MOMENTS" / "CRAFTED BY TRADITION"；左侧小字"EST. 1902" / "HAPPOSHU" / "ALC. 5.5% / 350ml"；右侧装饰性英文"EXPERIMENTAL BY NATURE"斜向排列；罐身日文"龍星麦酒"保留为品牌标识。【质感要求】画面具有强烈的平面设计实验性和解构美学；复古复印纸质感与现代极简排版形成反差张力；点阵处理效果精细统一；整体如艺术展览级别的限量版海报。',
    negative_prompt: '低质量, 模糊, 真实摄影反光, 变形文字, 杂乱背景, 噪点失真',
    model_name: 'Seedream 5.0 Pro',
    aspect_ratio: '3:4',
    parameters: {
      aspect_ratio: '3:4',
      resolution: '1536x2048',
      model: 'Seedream 5.0 Pro',
      reference_image: '/assets/community/case-beer-ref-can.webp',
      reference_type: '智能参考',
      reference_strength: 0.85,
      sampler: 'DPM++ 2M Karras',
      steps: 32,
      cfg_scale: 7.5,
      seed: 7681561564,
      engine: 'Jimeng / Koyo-Visual 5.0',
    },
    tags: ['潮流海报', '工业平面', '点阵艺术', '包装设计', '智能参考'],
    likes_count: 223,
    coins_count: 36,
    views_count: 8920,
    remix_count: 145,
    comments_count: 18,
    status: 'published',
    is_featured: true,
    created_at: '2026-09-04T10:28:00.000Z',
    updated_at: '2026-09-04T10:28:00.000Z',
    author_name: '即梦AI',
    author_avatar: '/assets/avatars/default-01.svg',
    author_username: 'jimeng_ai',
    author_id: 'usr_jimeng_ai',
    author_bio: '即梦 AI 官方精选创作与参数解析实验室',
    author_followers: 12890,
  },
  {
    id: 'case_cinema_vintage_70s',
    creation_id: 'cr_cinema_vintage_02',
    user_id: 'usr_lenscraft',
    title: '70年代复古电影胶片肖像',
    description: '柯达 Portra 400 经典暖调，柔和丁达尔光晕与自然大光圈散景。',
    media_type: 'image',
    media_url: '/assets/cinema/70s_cinema_prime.webp',
    cover_url: '/assets/cinema/70s_cinema_prime.webp',
    prompt: '70年代复古电影质感胶片写真，柯达 Portra 400 暖调颗粒，柔和丁达尔光晕，电影级散景虚化，大光圈定焦镜头摄影，暖色调，胶片颗粒感，高光溢出。',
    negative_prompt: '数字塑料感, 过度锐化, 灰暗, 偏色',
    model_name: 'FLUX.1 Cinematic',
    aspect_ratio: '16:9',
    parameters: {
      aspect_ratio: '16:9',
      resolution: '2048x1152',
      model: 'FLUX.1 Cinematic',
      sampler: 'Euler a',
      steps: 28,
      cfg_scale: 6.5,
      seed: 9382104,
      engine: 'FLUX Schnell Ultra',
    },
    tags: ['电影质感', '胶片写真', '复古光影', '大光圈'],
    likes_count: 188,
    coins_count: 24,
    views_count: 5410,
    remix_count: 89,
    comments_count: 12,
    status: 'published',
    is_featured: true,
    created_at: '2026-09-08T14:15:00.000Z',
    updated_at: '2026-09-08T14:15:00.000Z',
    author_name: 'LensCraft 影像所',
    author_avatar: '/assets/avatars/default-02.svg',
    author_username: 'lenscraft_studio',
    author_id: 'usr_lenscraft',
    author_bio: '探索胶片光学与数字渲染的交融之美',
    author_followers: 5420,
  },
  {
    id: 'case_industrial_macro',
    creation_id: 'cr_industrial_macro_03',
    user_id: 'usr_minimal_design',
    title: '蔡司大画幅工业微距美学',
    description: '极致微距与工业美学，冷调金属拉丝质感与光影折射棚拍。',
    media_type: 'image',
    media_url: '/assets/cinema/premium_large_format_digital.webp',
    cover_url: '/assets/cinema/premium_large_format_digital.webp',
    prompt: '极致微距与工业美学，德系蔡司大画幅数码微距镜头，冷调金属拉丝质感与光影折射，高精度产品级棚拍，极简背景，锐利边缘，光影渐层。',
    negative_prompt: '杂乱反光, 灰尘划痕, 模糊失焦',
    model_name: 'Midjourney v6.1',
    aspect_ratio: '4:3',
    parameters: {
      aspect_ratio: '4:3',
      resolution: '1920x1440',
      model: 'Midjourney v6.1',
      sampler: 'DPM++ SDE Karras',
      steps: 35,
      cfg_scale: 8.0,
      seed: 1047192,
      engine: 'Midjourney Turbo',
    },
    tags: ['工业设计', '蔡司微距', '金属质感', '商业摄影'],
    likes_count: 156,
    coins_count: 18,
    views_count: 4290,
    remix_count: 67,
    comments_count: 9,
    status: 'published',
    is_featured: true,
    created_at: '2026-09-11T09:40:00.000Z',
    updated_at: '2026-09-11T09:40:00.000Z',
    author_name: 'Minimal Industrial',
    author_avatar: '/assets/avatars/default-03.svg',
    author_username: 'minimal_industrial',
    author_id: 'usr_minimal_design',
    author_bio: '专注硬核工业品与极简材质视觉表达',
    author_followers: 3820,
  },
  {
    id: 'case_cyberpunk_rain_video',
    creation_id: 'cr_cyberpunk_video_04',
    user_id: 'usr_cyber_motion',
    title: '霓虹赛博雨夜宽银幕分镜',
    description: '未来赛博都市雨夜，霓虹倒影与宽银幕变形镜头光斑，慢动作电影运镜。',
    media_type: 'video',
    media_url: '/assets/cinema/classic_anamorphic.webp',
    cover_url: '/assets/cinema/classic_anamorphic.webp',
    prompt: '未来赛博都市雨夜，霓虹倒影，宽银幕变形镜头光斑，雨滴从镜头滑落，慢动作电影运镜，全景深，冷暖对比色调。',
    negative_prompt: '画面卡顿, 噪点块, 画面拉伸变形',
    model_name: 'Sora 2.0 Turbo',
    aspect_ratio: '16:9',
    parameters: {
      aspect_ratio: '16:9',
      resolution: '1920x1080',
      model: 'Sora 2.0 Turbo',
      fps: 30,
      duration: '5s',
      camera_motion: 'Pan Right & Slow Push',
      engine: 'OpenAI Sora Video Engine',
    },
    tags: ['赛博朋克', '雨夜霓虹', '宽银幕', '电影运镜'],
    likes_count: 312,
    coins_count: 48,
    views_count: 12400,
    remix_count: 230,
    comments_count: 34,
    status: 'published',
    is_featured: true,
    created_at: '2026-09-13T18:20:00.000Z',
    updated_at: '2026-09-13T18:20:00.000Z',
    author_name: 'CyberMotion 动画组',
    author_avatar: '/assets/avatars/default-04.svg',
    author_username: 'cybermotion',
    author_id: 'usr_cyber_motion',
    author_bio: 'AI 影视动态分镜与科幻世界观构建',
    author_followers: 18900,
  },
  {
    id: 'case_zen_ink_modern',
    creation_id: 'cr_zen_ink_05',
    user_id: 'usr_zen_ink',
    title: '新中式东方禅意概念解构',
    description: '新中式禅意美学，水墨留白与工笔重彩碰撞，金箔肌理与松柏光影。',
    media_type: 'image',
    media_url: '/assets/cinema/vintage_prime.webp',
    cover_url: '/assets/cinema/vintage_prime.webp',
    prompt: '新中式禅意美学，水墨留白与工笔重彩碰撞，金箔肌理与松柏光影，东方意境概念艺术，纸张纤维肌理，典雅东方留白。',
    negative_prompt: '俗艳杂乱, 现代塑料感, 结构错误',
    model_name: 'Seedream 5.0 Pro',
    aspect_ratio: '3:4',
    parameters: {
      aspect_ratio: '3:4',
      resolution: '1536x2048',
      model: 'Seedream 5.0 Pro',
      sampler: 'DPM++ 2M Karras',
      steps: 30,
      cfg_scale: 7.0,
      seed: 8491023,
      engine: 'Jimeng / Koyo-Visual 5.0',
    },
    tags: ['新中式', '水墨禅意', '概念设计', '金箔肌理'],
    likes_count: 245,
    coins_count: 30,
    views_count: 6730,
    remix_count: 112,
    comments_count: 15,
    status: 'published',
    is_featured: true,
    created_at: '2026-09-15T11:00:00.000Z',
    updated_at: '2026-09-15T11:00:00.000Z',
    author_name: '墨境工作室',
    author_avatar: '/assets/avatars/default-05.svg',
    author_username: 'zen_ink_art',
    author_id: 'usr_zen_ink',
    author_bio: '东方意象当代数字艺术转译',
    author_followers: 8430,
  },
  {
    id: 'case_halation_diffusion',
    creation_id: 'cr_halation_06',
    user_id: 'usr_aura_lab',
    title: '柔焦光晕弥散梦幻氛围',
    description: '胶片光晕弥散效果，梦幻复古氛围感，柔焦高光溢出与暖光漫反射。',
    media_type: 'image',
    media_url: '/assets/cinema/halation_diffusion.webp',
    cover_url: '/assets/cinema/halation_diffusion.webp',
    prompt: '胶片光晕弥散效果，梦幻复古氛围感，柔焦高光溢出，暖光漫反射，杂志封面级排版构图，情绪叙事感。',
    negative_prompt: '冷硬死黑, 杂乱边缘, 欠曝',
    model_name: 'FLUX.1 Schnell',
    aspect_ratio: '1:1',
    parameters: {
      aspect_ratio: '1:1',
      resolution: '1536x1536',
      model: 'FLUX.1 Schnell',
      sampler: 'Euler',
      steps: 25,
      cfg_scale: 6.0,
      seed: 6271903,
      engine: 'FLUX Schnell Ultra',
    },
    tags: ['梦幻氛围', '柔焦弥散', '杂志封面', '光晕艺术'],
    likes_count: 198,
    coins_count: 22,
    views_count: 5120,
    remix_count: 78,
    comments_count: 11,
    status: 'published',
    is_featured: true,
    created_at: '2026-09-16T15:45:00.000Z',
    updated_at: '2026-09-16T15:45:00.000Z',
    author_name: 'Aura Visual Lab',
    author_avatar: '/assets/avatars/default-06.svg',
    author_username: 'aura_visual',
    author_id: 'usr_aura_lab',
    author_bio: '捕捉光线的呼吸与弥散情绪',
    author_followers: 6120,
  },
  {
    id: 'case_tilt_shift_creative',
    creation_id: 'cr_tilt_shift_07',
    user_id: 'usr_tiny_world',
    title: '移轴微缩城市创意摄影',
    description: '移轴摄影微缩模型质感，城市街道俯瞰与极窄景深，高饱和度玩具感都市。',
    media_type: 'image',
    media_url: '/assets/cinema/creative_tilt_lens.webp',
    cover_url: '/assets/cinema/creative_tilt_lens.webp',
    prompt: '移轴摄影，微缩景观模型质感，城市街道俯瞰，极窄景深，高饱和度玩具感都市生活，精致透视，模型微距感。',
    negative_prompt: '全景深, 扁平无层次, 灰暗',
    model_name: 'Midjourney v6.1',
    aspect_ratio: '16:9',
    parameters: {
      aspect_ratio: '16:9',
      resolution: '2048x1152',
      model: 'Midjourney v6.1',
      sampler: 'DPM++ 2M Karras',
      steps: 30,
      cfg_scale: 7.0,
      seed: 4819203,
      engine: 'Midjourney Turbo',
    },
    tags: ['移轴摄影', '微缩模型', '俯瞰视角', '创意摄影'],
    likes_count: 172,
    coins_count: 16,
    views_count: 4580,
    remix_count: 63,
    comments_count: 8,
    status: 'published',
    is_featured: false,
    created_at: '2026-09-18T08:12:00.000Z',
    updated_at: '2026-09-18T08:12:00.000Z',
    author_name: 'TinyWorld 移轴社',
    author_avatar: '/assets/avatars/default-07.svg',
    author_username: 'tiny_world',
    author_id: 'usr_tiny_world',
    author_bio: '用微缩移轴的视角重新审视世界',
    author_followers: 4310,
  },
  {
    id: 'case_swirl_bokeh_portrait',
    creation_id: 'cr_swirl_bokeh_08',
    user_id: 'usr_vintage_bokeh',
    title: '八羽怪旋转焦外唯美肖像',
    description: '苏联经典八羽怪镜头独特的旋转焦外光斑，梦幻逆光轮廓与情绪人像。',
    media_type: 'image',
    media_url: '/assets/cinema/swirl_bokeh_portrait.webp',
    cover_url: '/assets/cinema/swirl_bokeh_portrait.webp',
    prompt: '苏联八羽怪经典镜头，独特的旋转焦外光斑，梦幻逆光轮廓，情绪感人物肖像，高光边缘色散，胶片色彩。',
    negative_prompt: '呆板虚化, 塑料人皮, 惨白光照',
    model_name: 'Seedream 5.0 Pro',
    aspect_ratio: '3:4',
    parameters: {
      aspect_ratio: '3:4',
      resolution: '1536x2048',
      model: 'Seedream 5.0 Pro',
      sampler: 'DPM++ 2M Karras',
      steps: 32,
      cfg_scale: 7.5,
      seed: 3918204,
      engine: 'Jimeng / Koyo-Visual 5.0',
    },
    tags: ['旋转焦外', '八羽怪', '胶片人像', '情绪摄影'],
    likes_count: 210,
    coins_count: 28,
    views_count: 5890,
    remix_count: 94,
    comments_count: 14,
    status: 'published',
    is_featured: false,
    created_at: '2026-09-19T16:30:00.000Z',
    updated_at: '2026-09-19T16:30:00.000Z',
    author_name: 'Vintage Bokeh 光学社',
    author_avatar: '/assets/avatars/default-08.svg',
    author_username: 'vintage_bokeh',
    author_id: 'usr_vintage_bokeh',
    author_bio: '老镜头玄学与光斑收集狂人',
    author_followers: 5120,
  },
];
